package com.example.fxcitydemo.gameworld;

import java.util.Set;

public enum Type {
  TREE, GROUND, GROUND_FONT,

//  TERRAIN,

  TESSA, CLANCY, YANG,
  LOCOMOTIVE, CART,
  BULLET, TANK_M7, TANK_M7_SHELL, LAUNCHER,
  HELICOPTER_APACHE, HELICOPTER_APACHE_MISSILE, LAUNCHER_MISSILE,
  LATV, BATTLESHIP_SIEGFRIED, LASER_BEAM, BATTLESHIP_YAMATO, BATTLESHIP_YAMATO_MISSILE,
  BATTLESHIP_YAMATO_SHELL, F3, F3_MISSILE, //BATTLESHIP_FENRIR, BATTLESHIP_BRYNHILD,
  HELICOPTER_CHINOOK, CHINOOK_BULLET,
  SPACE_MARINE, SPACE_MARINE_BULLET, FIRE_BALL;

  public static Set<Type> getCharacters(){
    return Set.of(TESSA, CLANCY, YANG);
  }

  public static Set<Type> getAmmos(){
    return Set.of(BULLET, SPACE_MARINE_BULLET, CHINOOK_BULLET, TANK_M7_SHELL, LAUNCHER_MISSILE,
      HELICOPTER_APACHE_MISSILE, F3_MISSILE, FIRE_BALL, LASER_BEAM, BATTLESHIP_YAMATO_MISSILE,
      BATTLESHIP_YAMATO_SHELL);
  }

  public static Set<Type> getAirAmmos(){
    return Set.of(CHINOOK_BULLET, HELICOPTER_APACHE_MISSILE, FIRE_BALL, LASER_BEAM, BATTLESHIP_YAMATO_SHELL);
  }

  public static Set<Type> getUnits(){
    return Set.of(LOCOMOTIVE, CART,
      TANK_M7, LAUNCHER, HELICOPTER_APACHE, BATTLESHIP_YAMATO, BATTLESHIP_SIEGFRIED, SPACE_MARINE, HELICOPTER_CHINOOK, F3);
  }
}
